-- STILL WAITING — Snowflake setup
-- Run this entire worksheet once with the SYSADMIN role.

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS STILL_WAITING_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS STILL_WAITING;
CREATE SCHEMA IF NOT EXISTS STILL_WAITING.ANALYTICS;

USE WAREHOUSE STILL_WAITING_WH;
USE DATABASE STILL_WAITING;
USE SCHEMA ANALYTICS;

-- Keep every imported value as text. Parsing happens in a view so a single
-- malformed date cannot abort the full file load.
CREATE OR REPLACE TABLE RAW_INTAKES (
  ANIMAL_ID          VARCHAR,
  NAME_VALUE         VARCHAR,
  DATETIME_RAW       VARCHAR,
  MONTH_YEAR         VARCHAR,
  FOUND_LOCATION     VARCHAR,
  INTAKE_TYPE        VARCHAR,
  INTAKE_CONDITION   VARCHAR,
  ANIMAL_TYPE        VARCHAR,
  SEX_UPON_INTAKE    VARCHAR,
  AGE_UPON_INTAKE    VARCHAR,
  BREED              VARCHAR,
  COLOR              VARCHAR
);

CREATE OR REPLACE TABLE RAW_OUTCOMES (
  ANIMAL_ID          VARCHAR,
  NAME_VALUE         VARCHAR,
  DATETIME_RAW       VARCHAR,
  MONTH_YEAR         VARCHAR,
  DATE_OF_BIRTH      VARCHAR,
  OUTCOME_TYPE       VARCHAR,
  OUTCOME_SUBTYPE    VARCHAR,
  ANIMAL_TYPE        VARCHAR,
  SEX_UPON_OUTCOME   VARCHAR,
  AGE_UPON_OUTCOME   VARCHAR,
  BREED              VARCHAR,
  COLOR              VARCHAR
);

SELECT 'RAW_INTAKES' AS TABLE_NAME, COUNT(*) AS ROWS_LOADED FROM RAW_INTAKES
UNION ALL
SELECT 'RAW_OUTCOMES', COUNT(*) FROM RAW_OUTCOMES;
