-- STILL WAITING — Transform raw Austin Animal Center records into dog stays.
-- Run after both CSV files have been loaded into the raw tables.

USE ROLE SYSADMIN;
USE WAREHOUSE STILL_WAITING_WH;
USE DATABASE STILL_WAITING;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW DOG_STAYS AS
WITH parsed_intakes AS (
  SELECT
    ANIMAL_ID,
    NAME_VALUE,
    COALESCE(
      TRY_TO_TIMESTAMP_NTZ(DATETIME_RAW, 'MM/DD/YYYY HH12:MI:SS AM'),
      TRY_TO_TIMESTAMP_NTZ(DATETIME_RAW)
    ) AS INTAKE_AT,
    INTAKE_TYPE,
    INTAKE_CONDITION,
    ANIMAL_TYPE,
    SEX_UPON_INTAKE,
    AGE_UPON_INTAKE,
    BREED,
    COLOR,
    CASE
      WHEN AGE_UPON_INTAKE ILIKE '%year%' THEN
        TRY_TO_NUMBER(REGEXP_SUBSTR(AGE_UPON_INTAKE, '^[0-9]+')) * 365
      WHEN AGE_UPON_INTAKE ILIKE '%month%' THEN
        TRY_TO_NUMBER(REGEXP_SUBSTR(AGE_UPON_INTAKE, '^[0-9]+')) * 30
      WHEN AGE_UPON_INTAKE ILIKE '%week%' THEN
        TRY_TO_NUMBER(REGEXP_SUBSTR(AGE_UPON_INTAKE, '^[0-9]+')) * 7
      WHEN AGE_UPON_INTAKE ILIKE '%day%' THEN
        TRY_TO_NUMBER(REGEXP_SUBSTR(AGE_UPON_INTAKE, '^[0-9]+'))
      ELSE NULL
    END AS AGE_DAYS
  FROM RAW_INTAKES
  WHERE UPPER(TRIM(ANIMAL_TYPE)) = 'DOG'
),
ordered_intakes AS (
  SELECT
    *,
    ROW_NUMBER() OVER (
      PARTITION BY ANIMAL_ID
      ORDER BY INTAKE_AT
    ) AS INTAKE_SEQUENCE,
    LEAD(INTAKE_AT) OVER (
      PARTITION BY ANIMAL_ID
      ORDER BY INTAKE_AT
    ) AS NEXT_INTAKE_AT
  FROM parsed_intakes
  WHERE ANIMAL_ID IS NOT NULL
    AND INTAKE_AT IS NOT NULL
),
parsed_outcomes AS (
  SELECT
    ANIMAL_ID,
    COALESCE(
      TRY_TO_TIMESTAMP_NTZ(DATETIME_RAW, 'MM/DD/YYYY HH12:MI:SS AM'),
      TRY_TO_TIMESTAMP_NTZ(DATETIME_RAW)
    ) AS OUTCOME_AT,
    OUTCOME_TYPE,
    OUTCOME_SUBTYPE
  FROM RAW_OUTCOMES
  WHERE UPPER(TRIM(ANIMAL_TYPE)) = 'DOG'
)
SELECT
  i.ANIMAL_ID,
  i.INTAKE_SEQUENCE,
  i.INTAKE_AT,
  o.OUTCOME_AT,
  ROUND(DATEDIFF('MINUTE', i.INTAKE_AT, o.OUTCOME_AT) / 1440.0, 2) AS WAIT_DAYS,
  i.INTAKE_TYPE,
  i.INTAKE_CONDITION,
  o.OUTCOME_TYPE,
  o.OUTCOME_SUBTYPE,
  i.SEX_UPON_INTAKE,
  i.AGE_UPON_INTAKE,
  i.AGE_DAYS,
  CASE
    WHEN i.AGE_DAYS IS NULL THEN 'Unknown'
    WHEN i.AGE_DAYS <= 365 THEN 'Puppy'
    WHEN i.AGE_DAYS <= 1095 THEN 'Young'
    WHEN i.AGE_DAYS <= 2555 THEN 'Adult'
    ELSE 'Senior'
  END AS AGE_BAND,
  i.BREED,
  i.COLOR
FROM ordered_intakes i
JOIN parsed_outcomes o
  ON o.ANIMAL_ID = i.ANIMAL_ID
  AND o.OUTCOME_AT >= i.INTAKE_AT
  AND (i.NEXT_INTAKE_AT IS NULL OR o.OUTCOME_AT < i.NEXT_INTAKE_AT)
WHERE o.OUTCOME_AT IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY i.ANIMAL_ID, i.INTAKE_SEQUENCE
  ORDER BY o.OUTCOME_AT
) = 1;

-- Use complete calendar years so partial-year reporting does not distort trends.
CREATE OR REPLACE VIEW ANALYSIS_DOG_STAYS AS
SELECT *
FROM DOG_STAYS
WHERE YEAR(INTAKE_AT) BETWEEN 2014 AND 2024
  AND WAIT_DAYS >= 0;

-- Quality checks: every displayed result should be traceable to these counts.
SELECT
  (SELECT COUNT(*) FROM RAW_INTAKES) AS RAW_INTAKES,
  (SELECT COUNT(*) FROM RAW_OUTCOMES) AS RAW_OUTCOMES,
  (SELECT COUNT(*) FROM DOG_STAYS) AS MATCHED_DOG_STAYS,
  (SELECT COUNT(*) FROM ANALYSIS_DOG_STAYS) AS COMPLETE_YEAR_STAYS;

SELECT
  MIN(INTAKE_AT) AS FIRST_INTAKE,
  MAX(INTAKE_AT) AS LAST_INTAKE,
  MIN(WAIT_DAYS) AS SHORTEST_WAIT_DAYS,
  MAX(WAIT_DAYS) AS LONGEST_WAIT_DAYS
FROM ANALYSIS_DOG_STAYS;
